In [1]:
import datacube
import pandas as pd
import geopandas as gpd
from datetime import datetime, timedelta
from odc.geo import Geometry
from dea_tools.bandindices import calculate_indices
import os
import glob
from concurrent.futures import ProcessPoolExecutor, as_completed

import sys
sys.path.append(os.path.abspath('./Tools/dea_tools'))
from classification import collect_training_data

In [2]:
# check the right up-to-data function was imported
collect_training_data?

Signature:
collect_training_data(
    gdf: geopandas.geodataframe.GeoDataFrame,
    dc_query: dict[str, typing.Any],
    ncpus: int = 1,
    chunksize: int | None = 1,
    return_coords: bool = False,
    feature_func: <built-in function callable> = None,
    field: str = None,
    zonal_stats: Optional[str] = None,
    clean: bool = True,
    fail_threshold: float = 0.05,
    fail_ratio: float = 0.5,
    max_retries: int = 2,
    time_field: Optional[str] = None,
    time_delta: Optional[datetime.timedelta] = None,
) -> pandas.core.frame.DataFrame
Docstring:
This function provides methods for gathering training/validation data from the ODC over
geometries stored within a geopandas geodataframe. The function will return a
pandas.DataFrame where the index contains class labels and the columns contain
feature values generated by a user-defined `feature_func`.

- In the instance where ncpus > 1, the function will automatically run in parallel.
- Zonal statistics are supported where the provided vector file contains polygons, otherwise all
  pixel values are returned.
- Individual points/polygons can be loaded from different time ranges by passing both `time_field`
  and `time_delta` variables, resulting in a time-range calculated as time_field +- time_delta
- Implements a retry queue for samples that may fail due to i/o limitations or s3 read failures.

Parameters
----------
gdf : geopandas geodataframe
    geometry data in the form of a geopandas geodataframe. Must contain a class labels column,
    can optionally contain a column with time stamps, specified with the`time_field` param.
dc_query : dictionary
    Datacube query object, should not contain lat and long (x or y) variables as these
    are supplied by the 'gdf' variable.
ncpus : int
    The number of cpus/processes over which to parallelize the gathering
    of training data (only if ncpus is > 1). Use 'mp.cpu_count()' to determine the number of
    cpus available on a machine. Defaults to 1.
chunksize : int, optional
    Number of items submitted to each worker per batch when using
    multiprocessing. Larger values reduce inter-process overhead but
    may worsen load balancing for uneven task runtimes.
feature_func : function
    A function for generating feature layers that is applied to the data within
    the bounds of the input geometry. The 'feature_func' must accept a 'dc_query'
    object, and return a single xarray.Dataset or xarray.DataArray:

        def feature_function(query):
            dc = datacube.Datacube(app='feature_layers')
            ds = dc.load(**query)
            ds = ds.mean('time')
            return ds

field : str
    Name of the column in the gdf that contains the class labels
return_coords : bool
    If True, then the training data will contain two extra columns 'x_coord' and
    'y_coord' corresponding to the x,y coordinate of each sample.
zonal_stats : string, optional
    An optional string giving the names of zonal statistics to calculate
    for each polygon. Default is None (all pixel values are returned). Supported
    values are 'mean', 'median', 'max', 'min'.
clean : bool
    Whether or not to remove missing values in the returned dataset. If True (default),
    training labels with any NaNs or Infs in the feature layers will be dropped
    from the dataset.
time_field : str, optional
    Name of the column containing timestamp data in the input gdf. Defaults to None.
    Note the time values must be in a datetime format that works with the `timedelta`
    variable. If time_field and time_delta aren't provided, then the dc_query object
    will require a 'time' value if the feature func loads from the datacube.
time_delta : timedelta, optional
    Time delta used to match a data point with all the scenes falling between
    `time_stamp - time_delta` and `time_stamp + time_delta`. Defaults to None.
fail_threshold : float, default 0.05
    Silent read fails on S3 can result in some rows of the returned data containing NaN values.
    The'fail_threshold' fraction specifies a % of acceptable fails.
    e.g. Setting 'fail_threshold' to 0.05 means if >5% of the samples in the training dataset
    fail then those samples will be returned to the multiprocessing queue. Below this fraction
    the function will accept the failures and return the results.
fail_ratio: float
    A float between 0 and 1 that defines if a given training sample has failed.
    Default is 0.5, which means if 50 % of the measurements in a given sample return null
    values, and the number of total fails is more than the fail_threshold, the samplewill be
    passed to the retry queue.
max_retries: int, default 2
    Maximum number of times to retry collecting samples. This number is invoked
    if the 'fail_threshold' is not reached.

Returns
--------
pandas.DataFrame
    Where the index contains class labels and the columns contain feature values
File:      ~/dev/Tools/dea_tools/classification.py
Type:      function

In [3]:
samples = gpd.read_file('test_sample_locations.geojson')
samples=samples.to_crs('EPSG:3577')
samples = samples.rename(columns={"class": "label"}) # name 'class' gives issues later on
samples.head()

   label                  geometry
0      1  POINT (1853295 -2953725)
1      1  POINT (1246755 -3990375)
2      1   POINT (775455 -2537445)
3      1  POINT (1960095 -2988915)
4      1  POINT (1509135 -3261075)

In [4]:
# add time column - for simplicity, only one date for all

samples['date'] = datetime(2024,7,1)
samples.head(3)

   label                  geometry       date
0      1  POINT (1853295 -2953725) 2024-07-01
1      1  POINT (1246755 -3990375) 2024-07-01
2      1   POINT (775455 -2537445) 2024-07-01

In [5]:
def feat_func(dc_query):
    dc = datacube.Datacube(app='feature_layers')
    ds_ard = dc.load(**dc_query)
    
    ds_ard = calculate_indices(
        ds_ard,
        index=['NDVI', 'NDWI', 'MNDWI'],
        drop=False,
        collection='ga_ls_3',
        verbose=False
    )

    # add time as band so it will returned in output dataframe
    ds_ard['date_'] = ds_ard.time.dt.strftime("%Y-%m-%d").broadcast_like(ds_ard["nbart_blue"])
    
    return ds_ard#.squeeze(dim="time")

In [6]:
training_data = collect_training_data(
    gdf=samples.iloc[:10],
    dc_query={
        'product':'ga_ls9c_ard_3',
        'measurements':["nbart_blue","nbart_green","nbart_red","nbart_nir","nbart_swir_1","nbart_swir_2","oa_fmask"],
        'output_crs': "epsg:3577",
        'skip_broken_datasets':True
    },
    ncpus=1, 
    return_coords=True, 
    feature_func=feat_func,
    field='label',
    clean=False,
    time_field='date',
    time_delta=timedelta(days=15), # this can be set to include a whole year
)

Collecting training data in serial mode
Returning data without cleaning
Output shape:  (27, 14)

In [7]:
training_data

,nbart_blue,nbart_green,nbart_red,nbart_nir,nbart_swir_1,nbart_swir_2,oa_fmask,NDVI,NDWI,MNDWI,date_,x_coord,y_coord
label,,,,,,,,,,,,,
1,332,693,638,239,424,423,5,-0.454960,0.487124,0.240824,2024-06-18,1853295.0,-2953725.0
1,307,674,608,378,313,308,5,-0.233266,0.281369,0.365755,2024-07-04,1853295.0,-2953725.0
1,218,721,472,199,85,92,5,-0.406855,0.567391,0.789082,2024-06-17,1246755.0,-3990375.0
1,259,707,460,265,97,115,5,-0.268966,0.454733,0.758706,2024-06-26,1246755.0,-3990375.0
1,196,626,415,190,89,70,5,-0.371901,0.534314,0.751049,2024-07-03,1246755.0,-3990375.0
1,7694,7695,7864,7656,4572,3538,2,-0.013402,0.002541,0.254585,2024-07-12,1246755.0,-3990375.0
1,420,808,671,216,121,135,5,-0.512965,0.578125,0.739505,2024-06-20,775455.0,-2537445.0
1,431,871,711,254,86,100,5,-0.473575,0.548444,0.820272,2024-06-27,775455.0,-2537445.0
1,3303,3666,3952,4650,4530,3862,2,0.081144,-0.118326,-0.105417,2024-07-06,775455.0,-2537445.0
1,835,1833,2376,747,112,108,5,-0.521614,0.420930,0.884833,2024-07-13,775455.0,-2537445.0
1,3208,3304,3382,3784,3545,3340,2,0.056098,-0.067720,-0.035188,2024-06-27,1960095.0,-2988915.0
1,1378,1600,1563,1951,1477,1238,2,0.110415,-0.098845,0.039974,2024-07-13,1960095.0,-2988915.0
1,885,1370,1257,748,216,124,5,-0.253865,0.293673,0.727617,2024-06-26,1509135.0,-3261075.0
1,6727,6667,6659,6190,848,1010,2,-0.036501,0.037100,0.774318,2024-07-12,1509135.0,-3261075.0
1,1971,2481,2916,3337,2611,2509,2,0.067328,-0.147130,-0.025530,2024-06-20,745125.0,-2999055.0
1,6312,6199,6374,6318,4443,4474,2,-0.004412,-0.009507,0.165007,2024-07-06,745125.0,-2999055.0
1,505,1012,1245,259,1,11,5,-0.655585,0.592447,0.998026,2024-06-17,1621305.0,-2724435.0
1,421,429,361,116,36,34,5,-0.513627,0.574312,0.845161,2024-07-03,1621305.0,-2724435.0
1,739,1291,949,87,110,77,5,-0.832046,0.873730,0.842969,2024-06-19,-397905.0,-1974225.0
1,740,1296,933,108,73,97,5,-0.792507,0.846154,0.893353,2024-07-05,-397905.0,-1974225.0
1,792,1313,1000,243,339,197,5,-0.609010,0.687661,0.589588,2024-07-14,-397905.0,-1974225.0
1,1836,1548,1602,3031,1953,1878,2,0.308439,-0.323870,-0.115681,2024-06-20,2063925.0,-3046305.0
1,1845,1562,1622,3066,1960,1875,2,0.308020,-0.324978,-0.113004,2024-06-20,2063925.0,-3046305.0
1,3049,2987,2917,3248,1581,912,2,0.053690,-0.041860,0.307793,2024-07-06,2063925.0,-3046305.0
1,3043,2996,2919,3260,1577,886,2,0.055187,-0.042199,0.310300,2024-07-06,2063925.0,-3046305.0
1,347,767,677,94,88,158,5,-0.756161,0.781649,0.794152,2024-06-24,1554015.0,-2487495.0
1,457,872,695,182,221,169,5,-0.584949,0.654649,0.595608,2024-07-10,1554015.0,-2487495.0

### try with time submitted in query only

In [8]:
samples_2 = samples.drop(columns=['date'])
samples_2.head(3)

   label                  geometry
0      1  POINT (1853295 -2953725)
1      1  POINT (1246755 -3990375)
2      1   POINT (775455 -2537445)

In [9]:
training_data_2 = collect_training_data(
    gdf=samples.iloc[:100],
    dc_query={
        'product':'ga_ls9c_ard_3',
        'measurements':["nbart_blue","nbart_green","nbart_red","nbart_nir","nbart_swir_1","nbart_swir_2","oa_fmask"],
        'output_crs': "epsg:3577",
        'time':(datetime(2024,7,1)-timedelta(days=15),datetime(2024,7,1)+timedelta(days=15)),
        'skip_broken_datasets':True
    },
    ncpus=40, 
    return_coords=True, 
    feature_func=feat_func,
    field='label',
    clean=False, 
)

Collecting training data in parallel mode

  0%|          | 0/100 [00:00<?, ?it/s]

Percentage of possible fails after run 1 = 0.0 %
Returning data without cleaning
Output shape:  (293, 14)

In [10]:
training_data_2

,nbart_blue,nbart_green,nbart_red,nbart_nir,nbart_swir_1,nbart_swir_2,oa_fmask,NDVI,NDWI,MNDWI,date_,x_coord,y_coord
label,,,,,,,,,,,,,
1,332,693,638,239,424,423,5,-0.454960,0.487124,0.240824,2024-06-18,1853295.0,-2953725.0
1,307,674,608,378,313,308,5,-0.233266,0.281369,0.365755,2024-07-04,1853295.0,-2953725.0
1,218,721,472,199,85,92,5,-0.406855,0.567391,0.789082,2024-06-17,1246755.0,-3990375.0
1,259,707,460,265,97,115,5,-0.268966,0.454733,0.758706,2024-06-26,1246755.0,-3990375.0
1,196,626,415,190,89,70,5,-0.371901,0.534314,0.751049,2024-07-03,1246755.0,-3990375.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,348,570,500,871,414,275,1,0.270605,-0.208883,0.158537,2024-07-07,-53445.0,-1452915.0
1,350,566,496,860,413,272,1,0.268437,-0.206171,0.156282,2024-07-07,-53445.0,-1452915.0
1,781,1275,1381,1312,366,225,1,-0.025622,-0.014302,0.553931,2024-06-21,93435.0,-1241535.0
1,447,501,484,1018,312,148,0,0.355526,-0.340355,0.232472,2024-06-30,93435.0,-1241535.0
1,811,1168,1253,1276,410,208,1,0.009095,-0.044190,0.480355,2024-07-07,93435.0,-1241535.0

In [11]:
training_data_2.equals(training_data)

False